refactor!(std): now std::parse is not evaluable
Instead of using $(std::parse "$@") now a single std::parse "$@" is allowed.
This is a BREAKING CHANGE with previous versions of blib.

Also this commit include some minor consmetic changes.

Signed-off-by: Andrés J. Díaz <ajdiaz@ajdiaz.me>

diff --git a/src/std b/src/std
--- a/src/std
+++ b/src/std
@@ -64,12 +64,12 @@ std::mute () {
 
 # fun: std::strin <str1> <str2>
 # api: blib
-# txt: return true if `str1` is into `str2`, or false otherwise.
+# txt: return true if `str2` is into `str1`, or false otherwise.
 # opt: str1: the string which could be contain `str2` and wants to evaluate
 # opt: str2: the string to find into `str1`
 # use: std::strin "somelargestring" "some"
 std::strin () {
-  [ "${1//$2/}" != "${1}" ]
+  [[ "${1//$2/}" != "${1}" ]]
 }
 
 # fun: std::sleep <seconds>
@@ -109,23 +109,29 @@ std::timestamp () {
 # api: blib
 # txt: parse an argument string in the form key=value and promote this
 #      variables to environment. The key `name` is mandatory. If the
-#      first parameter has no key, key `name` is using by default.
-# use: std::parse "name=Jhon age=90"
+#      first parameter has no key, key `name` is using by default. The
+#      `name` parameter must be the first one.
+# use: std::parse "name=Jhon" "age=90"
 #      echo "$name has $age years old"
 std::parse () {
-  local hasname=false
-  local fst="$1"; shift
+  local key val
+  export name
+  name="${1#name=}"; shift
 
-  [ "${fst#name=}" != "${fst}" ] || fst="name=$fst"
+  for arg in "$@"; do
+    if std::strin "$arg" "="; then
+      IFS='=' read -d $'\0' -r key val <<< "$arg"
 
-  for arg in "$fst" "$@"; do
-    std::strin "$arg" "=" || err::trace "Invalid argument: $arg"
-    [ "${arg#name=}" != "${arg}" ] && hasname=true
-    echo -n "local ${arg/=/=\'}';"
+      val="${val%$'\n'}" # XXX dirty hack to avoid problems with last \n
+                         # and one line text.
+
+      [[ "${key/=/}" ]] || err::trace "Invalid argument: $arg"
+      if ! std::mute declare -p "$key"; then
+        err::trace "Variable '$key' is undefined (required to parse '$arg')"
+      fi
+      export "$key"="$val"
+    fi
   done
-  ${hasname} || err::trace "The parameter 'name' is mandatory"
-  shift
-  echo
 }
 
 # fun: std::run <command>
@@ -147,7 +153,7 @@ std::installed () {
 # api: blib
 # txt: return true if dir is empty
 std::is_dir_empty () {
-  for f in $1/*; do
+  for f in "$1"/*; do
     [ "$f" == "$1/*" ] && return 0
     return 1
   done
